profile: full
ceip_policy_disclosed: true # Installation fails if this is set to 'false'
buildservice:
  kp_default_repository: "csamp.azurecr.io/azure-build"
  kp_default_repository_username: "csamp"
  kp_default_repository_password: "o2uzGQu3SZFuY714O489FF6=NyyY89y3"
  tanzunet_username: "csamp@pivotal.io"
  tanzunet_password: "S0fitel4$"
  descriptor_name: "tap-1.0.0-full"
  enable_automatic_dependency_updates: true
supply_chain: basic

ootb_supply_chain_basic:
  registry:
    server: "csamp.azurecr.io"
    repository: "azure-dev"
  gitops:
    ssh_secret: ""

contour:
  envoy:
    service:
      type: LoadBalancer

learningcenter:
  ingressDomain: "learningcenter.tap.sampsoftware.io"

cnrs:
  domain_name: "apps.tap.sampsoftware.io"

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "tap.sampsoftware.io"
  app_config:
    app:
      baseUrl: http://tap-gui.tap.sampsoftware.io
    catalog:
      locations:
        - type: url
          target: https://github.com/sample-accelerators/tanzu-java-web-app/blob/main/catalog/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.tap.sampsoftware.io
      cors:
        origin: http://tap-gui.tap.sampsoftware.io

metadata_store:
  app_service_type: LoadBalancer # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer

grype:
  targetImagePullSecret: "tap-registry"